// ******************************************************************************************
// * This project is licensed under the GNU Affero GPL v3. Copyright © 2014 A3Wasteland.com *
// ******************************************************************************************
//	@file Name: territories.sqf
//	@file Author: AgentRev, Bewilderbeest

// Territory system definitions. See territory/README.md for more details.
//
// 1 - Territory marker name. Must begin with 'TERRITORY_'
// 2 - Descriptive name
// 3 - Monetary value
// 4 - Territory category, currently unused. See territory/README.md for details.

[
	["TERRITORY_THRONOS_CASTLE", "Thronos Castle", 500, "CASTLE"],
	//["TERRITORY_KASTRO_CASTLE", "Kastro Castle", 500, "CASTLE"],
	["TERRITORY_SW_AIRFIELD", "AAC Airfield", 500, "AIRFIELD"],
	["TERRITORY_MAIN_AIRBASE_SW", "Altis Airport (SW)", 750, "AIRBASE"],
	["TERRITORY_MAIN_AIRBASE_CENTER", "Altis Airport (Center)", 750, "AIRBASE"],
	["TERRITORY_MAIN_AIRBASE_NE", "Altis Airport (NE)", 750, "AIRBASE"],
	["TERRITORY_NE_AIRFIELD", "Molos Airfield", 500, "AIRFIELD"],
	["TERRITORY_SE_AIRFIELD", "Selakano Airfield", 500, "AIRFIELD"],
	["TERRITORY_NW_AIRFIELD", "Northwest Airfield", 500, "AIRFIELD"],
	["TERRITORY_SALTFLATS_AIRFIELD", "Saltflats", 500, "AIRFIELD"],
	["TERRITORY_WEST_POWER_PLANT", "West Power Plant", 500, "POWER"],
	["TERRITORY_CENTER_POWER_PLANT", "Center Power Plant", 500, "POWER"],
	["TERRITORY_IRAKLIA_RUINS", "Iraklia Ruins", 500, "RUINS"],
	["TERRITORY_ARTINARKI_RUINS", "Artinarki Ruins", 500, "RUINS"],
	["TERRITORY_MAGOS_TRANSMITTER", "Magos Transmitter", 500, "TRANSMITTER"],
	["TERRITORY_PYRSOS_TRANSMITTER", "Pyrsos Transmitter", 500, "TRANSMITTER"],
	["TERRITORY_OREOKASTRO_SEKTOR_1", "OREOKASTRO BASE Sektor 1", 100, "MILITARY_SECTOR"],
	["TERRITORY_OREOKASTRO_SEKTOR_2", "OREOKASTRO BASE Sektor 2", 120, "MILITARY_SECTOR"],
	["TERRITORY_OREOKASTRO_SEKTOR_3", "OREOKASTRO BASE Sektor 3", 150, "MILITARY_SECTOR"],
	["TERRITORY_OREOKASTRO_SEKTOR_4", "OREOKASTRO BASE Sektor 4", 200, "MILITARY_SECTOR"],
	["TERRITORY_OREOKASTRO_SEKTOR_5", "OREOKASTRO BASE Sektor 5", 150, "MILITARY_SECTOR"],
	["TERRITORY_OREOKASTRO_SEKTOR_6", "OREOKASTRO BASE Sektor 6", 120, "MILITARY_SECTOR"],
	["TERRITORY_OREOKASTRO_SEKTOR_7", "OREOKASTRO BASE Sektor 7", 120, "MILITARY_SECTOR"],
	["TERRITORY_OREOKASTRO_SEKTOR_8", "OREOKASTRO BASE Sektor 8", 500, "MILITARY_SECTOR"],
	["TERRITORY_OREOKASTRO_SEKTOR_9", "OREOKASTRO BASE Sektor 9", 200, "MILITARY_SECTOR"],
	["TERRITORY_OREOKASTRO_SEKTOR_10", "OREOKASTRO BASE Sektor 10", 100, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_1", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_2", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_3", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_4", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_5", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_6", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_7", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_8", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_9", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_10", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_11", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_12", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_13", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_14", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_15", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_16", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_17", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_18", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_19", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_20", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_21", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_22", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_23", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_24", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_25", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_26", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_27", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_28", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_29", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_30", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_31", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_32", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_ALTIS_SEKTOR_ALPHA_33", "ALTIS SEKTOR", 1500, "MILITARY_SECTOR"],
	["TERRITORY_MILITARY_RESEARCH", "Telos Military Base", 500, "MILITARY"]
]
